# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/ubuntu-14.04"

  config.vm.define "cs" do |cs|
    cs.vm.hostname = "cs"
    cs.vm.network "private_network", ip: "172.32.32.10"

    cs.vm.provision :ansible do |ansible|
      playbook = 'consul_server'

      ansible.verbose = "#{ENV['ANSIBLE_VERBOSE']}"
      ansible.playbook = "ansible/#{playbook}.yml"
      ansible.inventory_path = 'ansible/multimachine.ini'
      ansible.limit = 'consul_server'
    end
  end

  # config.vm.define "n2" do |n2|
  #   n2.vm.hostname = "n2"
  #   n2.vm.network "private_network", ip: "172.32.32.11"
  # end

end
