# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 8301, host: 18301
  config.vm.network "forwarded_port", guest: 8302, host: 18302
  config.vm.network "forwarded_port", guest: 8400, host: 18400
  config.vm.network "forwarded_port", guest: 8500, host: 18500
  config.vm.network "forwarded_port", guest: 8600, host: 18600

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "172.16.0.11"
  #config.vm.network "private_network", ip: "192.168.32.11"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #

  config.vm.provision :ansible do |ansible|
    playbook = 'docker'

    if ENV.key?('ANSIBLE_PLAYBOOK')
      playbook = ENV['ANSIBLE_PLAYBOOK']
    end

    ansible.verbose = "#{ENV['ANSIBLE_VERBOSE']}"
    ansible.playbook = "../ansible/#{playbook}.yml"
    ansible.inventory_path = '../ansible/docker.ini'
    ansible.limit = 'vagrant'
  end

  # https://blog.codecentric.de/en/2014/01/docker-networking-made-simple-3-ways-connect-lxc-containers/
  # TODO move to ansible
  # config.vm.provision :shell, :inline => 'echo DOCKER_OPTS="-bip=192.168.32.10/24" > /etc/default/docker'
  # config.vm.provision :shell, :inline => '
  # echo ip addr del 192.168.32.10/24 dev eth1 > /etc/rc.local
  # echo ip link set eth1 master docker0 >> /etc/rc.local
  # echo service docker restart >> /etc/rc.local
  # chmod +x /etc/rc.local 2> /dev/null'
  # config.vm.provision :shell, :inline => '/etc/rc.local'

end
